<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Folder extends Model
{
    protected $fillable = [
        'name',
        'description',
        'owner'
    ];

    static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($folder) {
            $folder->owner = auth()->user()->id;
            $folder->save();
        });
    }

    public function owner(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class, 'owner', 'id');
    }

    public function materials()
    {
        return $this->hasMany(Material::class);
    }
}
